# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{woot_sync}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason T. Calhoun"]
  s.date = %q{2010-10-30}
  s.description = %q{WootSync is a library with common methods for interacting with Woot.com.}
  s.email = %q{jtcalhoun@tacostadium.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config/settings.yml",
     "lib/woot_sync.rb",
     "lib/woot_sync/base.rb",
     "lib/woot_sync/image.rb",
     "lib/woot_sync/shops.rb",
     "test/helper.rb",
     "test/image_test.rb",
     "test/shops_test.rb",
     "woot_sync.gemspec"
  ]
  s.homepage = %q{http://wootspy.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{WootSync is a library with common methods for interacting with Woot.com.}
  s.test_files = [
    "test/helper.rb",
     "test/image_test.rb",
     "test/shops_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["= 3.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["= 3.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["= 3.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

