client:
    credentials:    []
    site_host:      http://wootspy.com
    user_agent:     %{lib}

parser:
    statuses:       ['On Sale', 'Sold Out', 'Ended']
    timezone:       America/Chicago
    images:
        thumbnail:  [128,  96]
        standard:   [456, 342]
        detail:     [768, 576]

shops:
    - woot:
        host:       http://www.woot.com
        epoch:      2006-02-22T06:00:00Z
        expiry:     86400
        source:     [salerss, http://api.woot.com/1/sales/current.rss/www.woot.com]

    - wine:
        host:       http://wine.woot.com
        epoch:      2006-05-22T05:00:00Z
        expiry:     604800
        source:     [salerss, http://api.woot.com/1/sales/current.rss/wine.woot.com]

    - shirt:
        host:       http://shirt.woot.com
        epoch:      2007-07-20T05:00:00Z
        expiry:     86400
        source:     [salerss, http://api.woot.com/1/sales/current.rss/shirt.woot.com]

    - sellout:
        host:       http://sellout.woot.com
        epoch:      2007-09-13T05:00:00Z
        expiry:     86400
        source:     [homepage, http://sellout.woot.com]

    - kids:
        host:       http://kids.woot.com
        epoch:      2009-08-18T05:00:00Z
        expiry:     86400
        source:     [salerss, http://api.woot.com/1/sales/current.rss/kids.woot.com]
