#--
#  settings.yml
#  woot_sync-gem
#
#  Created by Jason T. Calhoun on 2010-06-25.
#  Copyright 2010 Taco Stadium. All rights reserved.
#++

images:
    extname:        .jpg
    suffixes:
        thumbnail:  [128,  96]
        standard:   [456, 342]
        detail:     [768, 576]

shops:
    - woot:
        host:       http://www.woot.com
        epoch:      2006-02-22T06:00:00Z
        expiry:     86400

    - wine:
        host:       http://wine.woot.com
        epoch:      2006-05-22T05:00:00Z
        expiry:     604800

    - shirt:
        host:       http://shirt.woot.com
        epoch:      2007-07-20T05:00:00Z
        expiry:     86400

    - sellout:
        host:       http://sellout.woot.com
        epoch:      2007-09-13T05:00:00Z
        expiry:     86400

    - kids:
        host:       http://kids.woot.com
        epoch:      2009-08-18T05:00:00Z
        expiry:     86400

user_agent:         WootSync/%s
